export const SET_SELECTED_SCHEDULE_ROUTE_ID = 'SET_SELECTED_SCHEDULE_ROUTE_ID';
export const SET_SELECTED_SCHEDULE = 'SET_SELECTED_SCHEDULE';
export const CLEAR_SCHEDULE = 'CLEAR_SCHEDULE';
export const SET_SCHEDULE_ERROR = 'SET_SCHEDULE_ERROR';

export const SET_SELECTED_ROUTE_BY_ID = 'SET_SELECTED_ROUTE_BY_ID';
export const CLEAR_SELECTED_ROUTE = 'CLEAR_SELECTED_ROUTE';
export const SET_ROUTE_LIST = 'FETCH_ROUTE_LIST';
export const TOGGLE_ROUTE_LIST_VISIBILITY = 'TOGGLE_ROUTE_LIST_VISIBILITY';
export const FILTER_ROUTE_LIST_BY_NUMBER_TEMPLATE = 'FILTER_ROUTE_LIST_BY_NUMBER_TEMPLATE';
export const CLEAR_ROUTE_LIST_FILTER = 'CLEAR_ROUTE_LIST_FILTER';


export const SET_STOP_LIST = 'SET_STOP_LIST';
export const TOGGLE_STOP_LIST_VISIBILITY = 'TOGGLE_STOP_LIST_VISIBILITY';
export const FILTER_STOP_LIST_BY_NAME_TEMPLATE = 'FILTER_STOP_LIST_BY_NAME_TEMPLATE';
export const CLEAR_STOP_LIST_FILTER = 'CLEAR_STOP_LIST_FILTER';


export const SET_CITY_LIST = 'SET_CITY_LIST';