export const SET_SELECTED_SCHEDULE = 'SET_SELECTED_SCHEDULE';

export const FETCH_ROUTE_LIST = 'FETCH_ROUTE_LIST';
export const TOGGLE_ROUTE_LIST_VISIBILITY = 'TOGGLE_ROUTE_LIST_VISIBILITY';
export const FILTER_ROUTE_LIST_BY_NUMBER_TEMPLATE = 'FILTER_ROUTE_LIST_BY_NUMBER_TEMPLATE';
export const CLEAR_ROUTE_LIST_FILTER = 'CLEAR_ROUTE_LIST_FILTER';


export const FETCH_STOP_LIST = 'FETCH_STOP_LIST';
export const TOGGLE_STOP_LIST_VISIBILITY = 'TOGGLE_STOP_LIST_VISIBILITY';
export const FILTER_STOP_LIST_BY_NAME_TEMPLATE = 'FILTER_STOP_LIST_BY_NAME_TEMPLATE';
export const CLEAR_STOP_LIST_FILTER = 'CLEAR_STOP_LIST_FILTER';
